lists/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from lists import views

urlpatterns = [
    # Examples:
    url(r'^(\d+)/$', views.viewList, name='view_list'),
    url(r'^new$', views.newList, name='new_list'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^admin/', include(admin.site.urls)),
]

superlists/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from lists import views as listsViews

urlpatterns = [
    # Examples:
    url(r'^$', listsViews.homePage, name='home'),
    url(r'^lists/', include('lists.urls')),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^admin/', include(admin.site.urls)),
]

lists/models.py
from django.db import models

# Create your models here.

class List(models.Model):
    pass

class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

lists/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from lists.models import Item,List
from django.core.exceptions import ValidationError

# Create your views here.

def homePage(request):
    return render(request, 'home.html')

def viewList(request,listID):
    myList = List.objects.get(id=listID)
    #items = Item.objects.filter(list = myList)
    error = None
    if request.method == 'POST':
        try:
            item = Item(text=request.POST['item_text'], list = myList)
            item.full_clean()
            item.save()
            return redirect('view_list', myList.id)
        except ValidationError:
            error = "You can't have an empty list item!"
    return  render(request, 'list.html', {'list': myList, 'error': error,} )

def newList(request):
    myList = List.objects.create()
    item = Item.objects.create(text=request.POST['item_text'], list = myList)
    try:
        item.full_clean()
    except ValidationError:
        myList.delete()
        error = "You can't have an empty list item!"
        return render(request, 'home.html', {'error': error,})

    return redirect('view_list', myList.id)

lists/templates/base.html
<html>
  <header>
    <title>To-Do lists</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/static/base.css" rel="stylesheet" media="screen">
  </header>
  <body>
  <div class="container">
  <div class="row">
  <div class="col-md-6 col-md-offset-3 jumbotron">
  <div class="text-center">
  <h1>{% block header_text %}{% endblock %}</h1>
  <form method="POST" action="{% block form_action %}{% endblock %}">
  <input name="item_text" id="id_new_item"
  placeholder="Enter a to-do item" class="form-control input-lg"
  />
  {% csrf_token %}
  {% if error %}
  <div class="form-group has-error">
    <span class="help-block">{{ error }}</span>
  </div>
  {% endif %}
  </form>
  </div>
  </div>
  </div>
  <div class="row">
  <div class="col-md-6 col-md-offset-3">
  {% block table %}
  {% endblock %}
  </div>
  </div>
  </div>
  </body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a New To-Do List{% endblock %}
{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do List{% endblock %}
{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
  <table id="id_list_table" class="table">
    {% for item in list.item_set.all %}
    <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
    {% endfor %}
  </table>
{% endblock %}